name: infomr
channels:
  - anaconda
  - plotly
  - open3d-admin
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.7.3
  - numpy=1.24.3
  - open3d=0.15.1
  - pandas=2.0.3
  - pip=24.2
  - plotly=5.24.1
  - pynndescent=0.5.13
  - python>=3.8.19, <=3.12.6 
  - requests=2.32.3
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - seaborn=0.13.2
  - setuptools=72.1.0
  - streamlit=1.39.0
  - tqdm=4.66.5
  - wheel=0.43.0
  - wxpython=4.2.1
  - pip:
      - pymeshlab==2023.12.post1
      - pyvista==0.44.1
      - pyviz-comms==3.0.3
      - stpyvista==0.0.9
      - vedo==2024.5.2
      - vtk==9.3.1
